require "nxt_support/models/email"
require "nxt_support/models/uuid"
require "nxt_support/models/safely_find_or_createable"
require "nxt_support/models/indifferently_accessible_json_attrs"
require "nxt_support/models/assignable_values"
require "nxt_support/models/preprocess_attributes"
require "nxt_support/models/duration_attribute_accessor"
